/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RevenueEntry {
  'id' : bigint,
  'accountId' : bigint,
  'description' : string,
  'timestamp' : bigint,
  'amount' : number,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SubscriptionPlan {
  'id' : bigint,
  'features' : Array<string>,
  'name' : string,
  'tier' : SubscriptionTier,
  'description' : string,
  'isActive' : boolean,
  'priceInCents' : bigint,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'inactive' : null };
export type SubscriptionTier = { 'annual' : null } |
  { 'monthly' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TwitchAccount {
  'id' : bigint,
  'status' : TwitchAccountStatus,
  'username' : string,
  'owner' : Principal,
  'accountType' : { 'affiliate' : null } |
    { 'partner' : null },
}
export type TwitchAccountStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'suspended' : null };
export interface UserProfile {
  'subscriptionEndDate' : [] | [bigint],
  'name' : string,
  'subscriptionTier' : [] | [SubscriptionTier],
  'subscriptionStatus' : SubscriptionStatus,
  'stripeCustomerId' : [] | [string],
  'subscriptionStartDate' : [] | [bigint],
  'isOwner' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRevenueEntry' : ActorMethod<[bigint, number, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkSubscriptionStatus' : ActorMethod<[], SubscriptionStatus>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createStripeSubscription' : ActorMethod<[bigint], string>,
  'createSubscriptionPlan' : ActorMethod<
    [string, string, SubscriptionTier, bigint, Array<string>],
    bigint
  >,
  'createTwitchAccount' : ActorMethod<
    [string, { 'affiliate' : null } | { 'partner' : null }],
    bigint
  >,
  'deleteSubscriptionPlan' : ActorMethod<[bigint], undefined>,
  'getActiveSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlan>>,
  'getAllRevenueEntries' : ActorMethod<[], Array<RevenueEntry>>,
  'getAllSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlan>>,
  'getAllTwitchAccounts' : ActorMethod<[], Array<TwitchAccount>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRevenueEntry' : ActorMethod<[bigint], [] | [RevenueEntry]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscriptionPlan' : ActorMethod<[bigint], [] | [SubscriptionPlan]>,
  'getTwitchAccount' : ActorMethod<[bigint], [] | [TwitchAccount]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isUserOwner' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setUserOwnerStatus' : ActorMethod<[Principal, boolean], undefined>,
  'toggleSubscriptionPlanStatus' : ActorMethod<[bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSubscriptionPlan' : ActorMethod<
    [bigint, string, string, bigint, Array<string>, boolean],
    undefined
  >,
  'updateTwitchAccountStatus' : ActorMethod<
    [bigint, TwitchAccountStatus],
    undefined
  >,
  'upgradeTwitchAccount' : ActorMethod<
    [bigint, { 'affiliate' : null } | { 'partner' : null }],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];