/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'inactive' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const SubscriptionTier = IDL.Variant({
  'annual' : IDL.Null,
  'monthly' : IDL.Null,
});
export const SubscriptionPlan = IDL.Record({
  'id' : IDL.Nat,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'tier' : SubscriptionTier,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'priceInCents' : IDL.Nat,
});
export const RevenueEntry = IDL.Record({
  'id' : IDL.Nat,
  'accountId' : IDL.Nat,
  'description' : IDL.Text,
  'timestamp' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const TwitchAccountStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'suspended' : IDL.Null,
});
export const TwitchAccount = IDL.Record({
  'id' : IDL.Nat,
  'status' : TwitchAccountStatus,
  'username' : IDL.Text,
  'owner' : IDL.Principal,
  'accountType' : IDL.Variant({ 'affiliate' : IDL.Null, 'partner' : IDL.Null }),
});
export const UserProfile = IDL.Record({
  'subscriptionEndDate' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'subscriptionTier' : IDL.Opt(SubscriptionTier),
  'subscriptionStatus' : SubscriptionStatus,
  'stripeCustomerId' : IDL.Opt(IDL.Text),
  'subscriptionStartDate' : IDL.Opt(IDL.Nat),
  'isOwner' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRevenueEntry' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createStripeSubscription' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'createSubscriptionPlan' : IDL.Func(
      [IDL.Text, IDL.Text, SubscriptionTier, IDL.Nat, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createTwitchAccount' : IDL.Func(
      [IDL.Text, IDL.Variant({ 'affiliate' : IDL.Null, 'partner' : IDL.Null })],
      [IDL.Nat],
      [],
    ),
  'deleteSubscriptionPlan' : IDL.Func([IDL.Nat], [], []),
  'getActiveSubscriptionPlans' : IDL.Func(
      [],
      [IDL.Vec(SubscriptionPlan)],
      ['query'],
    ),
  'getAllRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
  'getAllSubscriptionPlans' : IDL.Func(
      [],
      [IDL.Vec(SubscriptionPlan)],
      ['query'],
    ),
  'getAllTwitchAccounts' : IDL.Func([], [IDL.Vec(TwitchAccount)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRevenueEntry' : IDL.Func([IDL.Nat], [IDL.Opt(RevenueEntry)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubscriptionPlan' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SubscriptionPlan)],
      ['query'],
    ),
  'getTwitchAccount' : IDL.Func([IDL.Nat], [IDL.Opt(TwitchAccount)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setUserOwnerStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'toggleSubscriptionPlanStatus' : IDL.Func([IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSubscriptionPlan' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Bool],
      [],
      [],
    ),
  'updateTwitchAccountStatus' : IDL.Func(
      [IDL.Nat, TwitchAccountStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const SubscriptionTier = IDL.Variant({
    'annual' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const SubscriptionPlan = IDL.Record({
    'id' : IDL.Nat,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'tier' : SubscriptionTier,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'priceInCents' : IDL.Nat,
  });
  const RevenueEntry = IDL.Record({
    'id' : IDL.Nat,
    'accountId' : IDL.Nat,
    'description' : IDL.Text,
    'timestamp' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const TwitchAccountStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const TwitchAccount = IDL.Record({
    'id' : IDL.Nat,
    'status' : TwitchAccountStatus,
    'username' : IDL.Text,
    'owner' : IDL.Principal,
    'accountType' : IDL.Variant({
      'affiliate' : IDL.Null,
      'partner' : IDL.Null,
    }),
  });
  const UserProfile = IDL.Record({
    'subscriptionEndDate' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'subscriptionTier' : IDL.Opt(SubscriptionTier),
    'subscriptionStatus' : SubscriptionStatus,
    'stripeCustomerId' : IDL.Opt(IDL.Text),
    'subscriptionStartDate' : IDL.Opt(IDL.Nat),
    'isOwner' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRevenueEntry' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createStripeSubscription' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'createSubscriptionPlan' : IDL.Func(
        [IDL.Text, IDL.Text, SubscriptionTier, IDL.Nat, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createTwitchAccount' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({ 'affiliate' : IDL.Null, 'partner' : IDL.Null }),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteSubscriptionPlan' : IDL.Func([IDL.Nat], [], []),
    'getActiveSubscriptionPlans' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionPlan)],
        ['query'],
      ),
    'getAllRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
    'getAllSubscriptionPlans' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionPlan)],
        ['query'],
      ),
    'getAllTwitchAccounts' : IDL.Func([], [IDL.Vec(TwitchAccount)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRevenueEntry' : IDL.Func([IDL.Nat], [IDL.Opt(RevenueEntry)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubscriptionPlan' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SubscriptionPlan)],
        ['query'],
      ),
    'getTwitchAccount' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TwitchAccount)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setUserOwnerStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'toggleSubscriptionPlanStatus' : IDL.Func([IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSubscriptionPlan' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Bool],
        [],
        [],
      ),
    'updateTwitchAccountStatus' : IDL.Func(
        [IDL.Nat, TwitchAccountStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };