/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface RevenueEntry {
    id: bigint;
    accountId: bigint;
    description: string;
    timestamp: bigint;
    amount: number;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface TwitchAccount {
    id: bigint;
    status: TwitchAccountStatus;
    username: string;
    owner: Principal;
    accountType: Variant_affiliate_partner;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface SubscriptionPlan {
    id: bigint;
    features: Array<string>;
    name: string;
    tier: SubscriptionTier;
    description: string;
    isActive: boolean;
    priceInCents: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    twitchUsername?: string;
    subscriptionEndDate?: bigint;
    name: string;
    subscriptionTier?: SubscriptionTier;
    subscriptionStatus: SubscriptionStatus;
    stripeCustomerId?: string;
    subscriptionStartDate?: bigint;
    isOwner: boolean;
}
export enum SubscriptionStatus {
    active = "active",
    cancelled = "cancelled",
    inactive = "inactive"
}
export enum SubscriptionTier {
    annual = "annual",
    monthly = "monthly"
}
export enum TwitchAccountStatus {
    pending = "pending",
    approved = "approved",
    suspended = "suspended"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_affiliate_partner {
    affiliate = "affiliate",
    partner = "partner"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addRevenueEntry(accountId: bigint, amount: number, description: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createStripeSubscription(planId: bigint): Promise<string>;
    createSubscriptionPlan(name: string, description: string, tier: SubscriptionTier, priceInCents: bigint, features: Array<string>): Promise<bigint>;
    createTwitchAccount(username: string, accountType: Variant_affiliate_partner): Promise<bigint>;
    deleteSubscriptionPlan(planId: bigint): Promise<void>;
    getActiveSubscriptionPlans(): Promise<Array<SubscriptionPlan>>;
    getAdminDashboardStats(): Promise<{
        totalUsers: bigint;
        totalRevenue: number;
        activeSubscriptions: bigint;
    }>;
    getAllRevenueEntries(): Promise<Array<RevenueEntry>>;
    getAllSubscriptionPlans(): Promise<Array<SubscriptionPlan>>;
    getAllTwitchAccounts(): Promise<Array<TwitchAccount>>;
    getAllUsersAdmin(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getRevenueEntry(revenueId: bigint): Promise<RevenueEntry | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSubscriptionPlan(planId: bigint): Promise<SubscriptionPlan | null>;
    getTwitchAccount(accountId: bigint): Promise<TwitchAccount | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    setUserOwnerStatus(user: Principal, isOwnerStatus: boolean): Promise<void>;
    toggleSubscriptionPlanStatus(planId: bigint): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateSubscriptionPlan(planId: bigint, name: string, description: string, priceInCents: bigint, features: Array<string>, isActive: boolean): Promise<void>;
    updateTwitchAccountStatus(accountId: bigint, status: TwitchAccountStatus): Promise<void>;
    upgradeTwitchAccount(accountId: bigint, accountType: Variant_affiliate_partner): Promise<void>;
}
import type { RevenueEntry as _RevenueEntry, StripeSessionStatus as _StripeSessionStatus, SubscriptionPlan as _SubscriptionPlan, SubscriptionStatus as _SubscriptionStatus, SubscriptionTier as _SubscriptionTier, TwitchAccount as _TwitchAccount, TwitchAccountStatus as _TwitchAccountStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addRevenueEntry(arg0: bigint, arg1: number, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRevenueEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRevenueEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createStripeSubscription(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createStripeSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStripeSubscription(arg0);
            return result;
        }
    }
    async createSubscriptionPlan(arg0: string, arg1: string, arg2: SubscriptionTier, arg3: bigint, arg4: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubscriptionPlan(arg0, arg1, to_candid_SubscriptionTier_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubscriptionPlan(arg0, arg1, to_candid_SubscriptionTier_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async createTwitchAccount(arg0: string, arg1: Variant_affiliate_partner): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTwitchAccount(arg0, to_candid_variant_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTwitchAccount(arg0, to_candid_variant_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteSubscriptionPlan(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubscriptionPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubscriptionPlan(arg0);
            return result;
        }
    }
    async getActiveSubscriptionPlans(): Promise<Array<SubscriptionPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSubscriptionPlans();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSubscriptionPlans();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminDashboardStats(): Promise<{
        totalUsers: bigint;
        totalRevenue: number;
        activeSubscriptions: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboardStats();
            return result;
        }
    }
    async getAllRevenueEntries(): Promise<Array<RevenueEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRevenueEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRevenueEntries();
            return result;
        }
    }
    async getAllSubscriptionPlans(): Promise<Array<SubscriptionPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscriptionPlans();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscriptionPlans();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTwitchAccounts(): Promise<Array<TwitchAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTwitchAccounts();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTwitchAccounts();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsersAdmin(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersAdmin();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersAdmin();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevenueEntry(arg0: bigint): Promise<RevenueEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueEntry(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueEntry(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionPlan(arg0: bigint): Promise<SubscriptionPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionPlan(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionPlan(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTwitchAccount(arg0: bigint): Promise<TwitchAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTwitchAccount(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTwitchAccount(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async setUserOwnerStatus(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserOwnerStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserOwnerStatus(arg0, arg1);
            return result;
        }
    }
    async toggleSubscriptionPlanStatus(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSubscriptionPlanStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSubscriptionPlanStatus(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateSubscriptionPlan(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: Array<string>, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionPlan(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionPlan(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateTwitchAccountStatus(arg0: bigint, arg1: TwitchAccountStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTwitchAccountStatus(arg0, to_candid_TwitchAccountStatus_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTwitchAccountStatus(arg0, to_candid_TwitchAccountStatus_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upgradeTwitchAccount(arg0: bigint, arg1: Variant_affiliate_partner): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeTwitchAccount(arg0, to_candid_variant_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeTwitchAccount(arg0, to_candid_variant_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_StripeSessionStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPlan_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPlan): SubscriptionPlan {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TwitchAccountStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TwitchAccountStatus): TwitchAccountStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TwitchAccount_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TwitchAccount): TwitchAccount {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionTier]): SubscriptionTier | null {
    return value.length === 0 ? null : from_candid_SubscriptionTier_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RevenueEntry]): RevenueEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionPlan]): SubscriptionPlan | null {
    return value.length === 0 ? null : from_candid_SubscriptionPlan_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TwitchAccount]): TwitchAccount | null {
    return value.length === 0 ? null : from_candid_TwitchAccount_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TwitchAccountStatus;
    username: string;
    owner: Principal;
    accountType: {
        affiliate: null;
    } | {
        partner: null;
    };
}): {
    id: bigint;
    status: TwitchAccountStatus;
    username: string;
    owner: Principal;
    accountType: Variant_affiliate_partner;
} {
    return {
        id: value.id,
        status: from_candid_TwitchAccountStatus_n14(_uploadFile, _downloadFile, value.status),
        username: value.username,
        owner: value.owner,
        accountType: from_candid_variant_n16(_uploadFile, _downloadFile, value.accountType)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    twitchUsername: [] | [string];
    subscriptionEndDate: [] | [bigint];
    name: string;
    subscriptionTier: [] | [_SubscriptionTier];
    subscriptionStatus: _SubscriptionStatus;
    stripeCustomerId: [] | [string];
    subscriptionStartDate: [] | [bigint];
    isOwner: boolean;
}): {
    twitchUsername?: string;
    subscriptionEndDate?: bigint;
    name: string;
    subscriptionTier?: SubscriptionTier;
    subscriptionStatus: SubscriptionStatus;
    stripeCustomerId?: string;
    subscriptionStartDate?: bigint;
    isOwner: boolean;
} {
    return {
        twitchUsername: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.twitchUsername)),
        subscriptionEndDate: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.subscriptionEndDate)),
        name: value.name,
        subscriptionTier: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.subscriptionTier)),
        subscriptionStatus: from_candid_SubscriptionStatus_n23(_uploadFile, _downloadFile, value.subscriptionStatus),
        stripeCustomerId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.stripeCustomerId)),
        subscriptionStartDate: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.subscriptionStartDate)),
        isOwner: value.isOwner
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    features: Array<string>;
    name: string;
    tier: _SubscriptionTier;
    description: string;
    isActive: boolean;
    priceInCents: bigint;
}): {
    id: bigint;
    features: Array<string>;
    name: string;
    tier: SubscriptionTier;
    description: string;
    isActive: boolean;
    priceInCents: bigint;
} {
    return {
        id: value.id,
        features: value.features,
        name: value.name,
        tier: from_candid_SubscriptionTier_n9(_uploadFile, _downloadFile, value.tier),
        description: value.description,
        isActive: value.isActive,
        priceInCents: value.priceInCents
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    annual: null;
} | {
    monthly: null;
}): SubscriptionTier {
    return "annual" in value ? SubscriptionTier.annual : "monthly" in value ? SubscriptionTier.monthly : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    suspended: null;
}): TwitchAccountStatus {
    return "pending" in value ? TwitchAccountStatus.pending : "approved" in value ? TwitchAccountStatus.approved : "suspended" in value ? TwitchAccountStatus.suspended : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    affiliate: null;
} | {
    partner: null;
}): Variant_affiliate_partner {
    return "affiliate" in value ? Variant_affiliate_partner.affiliate : "partner" in value ? Variant_affiliate_partner.partner : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    inactive: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "cancelled" in value ? SubscriptionStatus.cancelled : "inactive" in value ? SubscriptionStatus.inactive : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n31(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TwitchAccount>): Array<TwitchAccount> {
    return value.map((x)=>from_candid_TwitchAccount_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubscriptionPlan>): Array<SubscriptionPlan> {
    return value.map((x)=>from_candid_SubscriptionPlan_n7(_uploadFile, _downloadFile, x));
}
function to_candid_SubscriptionStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TwitchAccountStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TwitchAccountStatus): _TwitchAccountStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    twitchUsername?: string;
    subscriptionEndDate?: bigint;
    name: string;
    subscriptionTier?: SubscriptionTier;
    subscriptionStatus: SubscriptionStatus;
    stripeCustomerId?: string;
    subscriptionStartDate?: bigint;
    isOwner: boolean;
}): {
    twitchUsername: [] | [string];
    subscriptionEndDate: [] | [bigint];
    name: string;
    subscriptionTier: [] | [_SubscriptionTier];
    subscriptionStatus: _SubscriptionStatus;
    stripeCustomerId: [] | [string];
    subscriptionStartDate: [] | [bigint];
    isOwner: boolean;
} {
    return {
        twitchUsername: value.twitchUsername ? candid_some(value.twitchUsername) : candid_none(),
        subscriptionEndDate: value.subscriptionEndDate ? candid_some(value.subscriptionEndDate) : candid_none(),
        name: value.name,
        subscriptionTier: value.subscriptionTier ? candid_some(to_candid_SubscriptionTier_n3(_uploadFile, _downloadFile, value.subscriptionTier)) : candid_none(),
        subscriptionStatus: to_candid_SubscriptionStatus_n36(_uploadFile, _downloadFile, value.subscriptionStatus),
        stripeCustomerId: value.stripeCustomerId ? candid_some(value.stripeCustomerId) : candid_none(),
        subscriptionStartDate: value.subscriptionStartDate ? candid_some(value.subscriptionStartDate) : candid_none(),
        isOwner: value.isOwner
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    active: null;
} | {
    cancelled: null;
} | {
    inactive: null;
} {
    return value == SubscriptionStatus.active ? {
        active: null
    } : value == SubscriptionStatus.cancelled ? {
        cancelled: null
    } : value == SubscriptionStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TwitchAccountStatus): {
    pending: null;
} | {
    approved: null;
} | {
    suspended: null;
} {
    return value == TwitchAccountStatus.pending ? {
        pending: null
    } : value == TwitchAccountStatus.approved ? {
        approved: null
    } : value == TwitchAccountStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    annual: null;
} | {
    monthly: null;
} {
    return value == SubscriptionTier.annual ? {
        annual: null
    } : value == SubscriptionTier.monthly ? {
        monthly: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_affiliate_partner): {
    affiliate: null;
} | {
    partner: null;
} {
    return value == Variant_affiliate_partner.affiliate ? {
        affiliate: null
    } : value == Variant_affiliate_partner.partner ? {
        partner: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
